language: python

python: "3.7"
os: linux
dist: xenial

sudo: false
matrix:
  include:
    - env: RUN_TESTS=py.test --capture=sys tests
    - env: CONQUER_ENABLED=true CONQUER_WORKERS=1 RUN_TESTS=py.test --capture=sys tests
    - env: CONQUER_ENABLED=true CONQUER_WORKERS=2 RUN_TESTS=py.test --capture=sys tests

services:
  - docker
addons:
  apt:
    packages:
      - python-commandnotfound
      - python3-commandnotfound
before_install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then rm -rf /usr/local/include/c++; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew upgrade python; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then pip3 install virtualenv; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then virtualenv venv -p python3; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then source venv/bin/activate; fi
  - pip install -U pip
  - pip install -U coveralls
install:
  - pip install -Ur requirements.txt
  - python setup.py develop
  - rm -rf build
script:
  - $RUN_TESTS
